 runs-on: self-hosted

    steps:
      - name: hostname
        run: hostname
      # - name: Checkout code
      #   uses: actions/checkout@v4
      # - name: SSH
      #   env:
      #     SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      #     SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      #     SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      #     SSH_HOST: ${{ secrets.SSH_HOST }}
      #   run: |
      #     mkdir -p /home/runner/.ssh
      #     ssh-keyscan $SSH_HOST >> /home/runner/.ssh/known_hosts
      #     echo "$SSH_PRIVATE_KEY" > /home/runner/.ssh/github_actions
      #     chmod 600 /home/runner/.ssh/github_actions
      #     ssh-agent -a $SSH_AUTH_SOCK > /dev/null
      #     ssh -i /home/runner/.ssh/github_actions $SSH_USERNAME@$SSH_HOST "echo 'Hello from GitHub Actions'"
      
      - name: Deploy to server 2
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SERVER_2_HOST: ${{ secrets.SERVER_2_HOST }}
        run: |
          ssh-keyscan $SERVER_2_HOST >> ~/.ssh/known_hosts
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/github_actions
          chmod 600 ~/.ssh/github_actions
          ssh -i ~/.ssh/github_actions $SSH_USERNAME@$SERVER_2_HOST "cd /docker-compose-flask-app && git pull && docker compose up -d --build"
      # - name: Set up Go
      #   uses: actions/setup-go@v3
      #   with:
